x = int(input("Enter the value of X: "))
y = int(input("Entet the value of Y: "))
print(f"The value of X is {x} and value of Y is {y}")
print(f"The Arithmetic Operations on {x} and {y} are: \n")
print(f"Addition of {x} and {y}: ", x + y)
print(f"Subtraction of {x} and {y}:", x - y)
print(f"Multiplication of {x} and {y}: ", x * y)
print(f"Division of {x} and {y}: ", x / y)
print(f"Modulus of {x} and {y}: ", x % y)
print(f"Floor Division of {x} and {y}: ", x // y)
print(f"Exponent of {x} and {y}: ", x ** y)
